name: shop_hop_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Base
  google_fonts: ^6.1.0

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #ShopHop
  nb_utils: ^6.0.4
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.14
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.0

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "images/shophop/ic_app_icon.png"

flutter:


  uses-material-design: true

  assets:
   - images/shophop/
   - images/
   - images/shophop/img/
   - assets/shophop_data/
   - images/shophop/img/products/
   - images/shophop/img/products/shoes/
   - images/shophop/img/products/dress/
   - images/shophop/img/products/banners/
   - images/shophop/img/products/decor/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

